version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: white-flask-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-white_flask}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-white_flask_password}
      POSTGRES_DB: ${POSTGRES_DB:-white_flask_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-white_flask}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: