[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm@10.12.1 && pnpm build"

[build.env]
NODE_VERSION = "24.2.0"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "blog"
port = 3001
protocol = "TCP"
