[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && cd apps/blog && pnpm build"

[deploy]
startCommand = "cd apps/blog && pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "blog"