[variables]
NODE_VERSION = "24.2.0"

[build]
builder = "nixpacks"
buildCommand = "pnpm --filter blog build"

[deploy]
startCommand = "pnpm --filter blog start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "blog"
port = 3001
protocol = "TCP"
