[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && cd apps/backend && pnpm build"

[deploy]
startCommand = "cd apps/backend && pnpm start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "backend"