[build]
builder = "nixpacks"
buildCommand = "corepack enable && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
port = 3003
protocol = "TCP"
