[variables]
NODE_VERSION = "24.2.0"

[build]
builder = "nixpacks"
buildCommand = "pnpm --filter backend build && pnpm --filter backend db:migrate"

[deploy]
startCommand = "pnpm --filter backend start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
port = 3003
protocol = "TCP"
