[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm@10.12.1 && export PATH=$PATH:$(npm config get prefix)/bin && pnpm build"

[build.env]
NODE_VERSION = "24.2.0"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "admin"
port = 3002
protocol = "TCP"