[build]
builder = "nixpacks"
buildCommand = "corepack enable && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "admin"
port = 3002
protocol = "TCP"