[variables]
NODE_VERSION = "24.2.0"

[build]
builder = "nixpacks"
buildCommand = "pnpm --filter backend schema:generate && pnpm --filter admin build"

[deploy]
startCommand = "pnpm --filter admin start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "admin"
port = 3002
protocol = "TCP"
