name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build applications
        run: pnpm build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: railway link -p ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy Blog
        run: railway up --service blog --detach
        continue-on-error: false

      - name: Deploy Admin
        run: railway up --service admin --detach
        continue-on-error: false

      - name: Deploy Backend
        run: railway up --service backend --detach
        continue-on-error: false
