name: Railway Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check Token in Secrets
        run: |
          if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "❌ RAILWAY_TOKEN is not set in GitHub Secrets"
            exit 1
          else
            echo "✅ RAILWAY_TOKEN is set in GitHub Secrets"
          fi
      
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
      
      - name: Test Railway Version
        run: railway version
      
      - name: Test Railway Whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway whoami
      
      - name: List Railway Services
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "=== Listing all services in the project ==="
          railway service || echo "No services found or command failed"
          
      - name: Test Service Detection from Each Directory
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "=== Testing from blog directory ==="
          cd apps/blog
          railway status || echo "Status command failed"
          
          echo -e "\n=== Testing from admin directory ==="
          cd ../admin
          railway status || echo "Status command failed"
          
          echo -e "\n=== Testing from backend directory ==="
          cd ../backend
          railway status || echo "Status command failed"